name: share_blog
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fpdart: ^1.1.1
  supabase_flutter: ^2.10.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  equatable: ^2.0.7
  intl: ^0.20.2
  floor: ^1.5.0
  retrofit: ^4.7.2
  flutter_hooks: ^0.21.3+1
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  json_annotation: ^4.9.0
  logger: ^2.6.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.2.0
  awesome_dialog: ^3.2.1
  liquid_wave_animate_button: ^1.0.5
  get: ^4.7.2
  curved_navigation_bar: ^1.0.6
  markdown_widget: ^2.3.2+8
  flutter_markdown: ^0.7.7+1
  flutter_speed_dial: ^7.0.0
  read_more_text: ^0.0.5
  horizontal_card_pager: ^1.1.1
  vertical_card_pager: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.2.0
  floor_generator: ^1.5.0
  build_runner: ^2.5.4
  
  flutter_gen_runner: ^5.10.0
  
  json_serializable: ^6.9.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/